---
before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh
    - ./scripts/hiveos.sh {{ .Version }}

builds:
  - 
    id: default
    env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: dero-stratum-miner
    ldflags: -s -w -X github.com/whalesburg/dero-stratum-miner/internal/version.Version={{ .Version }} -X github.com/whalesburg/dero-stratum-miner/internal/version.Commit={{ .Commit }} -X github.com/whalesburg/dero-stratum-miner/internal/version.Date={{ .Date }} -X github.com/whalesburg/dero-stratum-miner/internal/version.BuiltBy=goreleaser
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "7"
  - 
    id: bsd
    env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: dero-stratum-miner
    ldflags: -s -w -X github.com/whalesburg/dero-stratum-miner/internal/version.Version={{ .Version }} -X github.com/whalesburg/dero-stratum-miner/internal/version.Commit={{ .Commit }} -X github.com/whalesburg/dero-stratum-miner/internal/version.Date={{ .Date }} -X github.com/whalesburg/dero-stratum-miner/internal/version.BuiltBy=goreleas
    flags: 
      - -trimpath
    goos:
      - freebsd
    goarch:
      - amd64
      - "386"
  - 
    id: hiveos
    env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: dero-stratum-miner
    ldflags: -s -w -X github.com/whalesburg/dero-stratum-miner/internal/version.Version={{ .Version }} -X github.com/whalesburg/dero-stratum-miner/internal/version.Commit={{ .Commit }} -X github.com/whalesburg/dero-stratum-miner/internal/version.Date={{ .Date }} -X github.com/whalesburg/dero-stratum-miner/internal/version.BuiltBy=goreleaser
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64

archives:
  # default
  - 
    name_template: "dero-stratum-miner-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    builds:
      - default
      - bsd
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - manpages/
      - completions
  # hiveos
  -
    id: hiveos
    name_template: "dero-stratum-miner-{{ .Version }}.hiveOS"
    builds:
      - hiveos
    format: tar.gz
    wrap_in_directory: dero-stratum-miner
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - src: 'hiveos/*'
        strip_parent: true

checksum:
  name_template: checksums.txt

nfpms:
  - 
    builds:
      - default
    file_name_template: "dero-stratum-miner-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    vendor: whalesburg
    homepage: https://whalesburg.com
    maintainer: whalesburg <pool@stratum.farm>
    description: Dero Stratum Miner
    license: MIT
    formats:
      - apk
      - deb
      - rpm

source:
  enabled: true

snapshot:
  name_template: "{{ incpatch .Version }}-devel"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Others
      order: 999